
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 15 22:38:59 CEST 2019
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int Y = 39;
  public static final int TIPOS = 32;
  public static final int DE = 2;
  public static final int MULT = 30;
  public static final int BRACKETR = 47;
  public static final int DEVOLVER = 5;
  public static final int EQUALS = 21;
  public static final int SUBPROGRAMAS = 31;
  public static final int PROGRAMA = 6;
  public static final int ENTERO = 7;
  public static final int SI = 14;
  public static final int FUNCION = 17;
  public static final int BRACKETL = 46;
  public static final int CIERTO = 27;
  public static final int ENTONCES = 3;
  public static final int LESS = 44;
  public static final int FIN = 8;
  public static final int MINUS = 34;
  public static final int COMIENZO = 38;
  public static final int SINO = 22;
  public static final int CONSTANTES = 36;
  public static final int ESCRIBIR = 37;
  public static final int PROCEDIMIENTO = 11;
  public static final int NUM = 9;
  public static final int PLUS = 33;
  public static final int IF = 18;
  public static final int ID = 20;
  public static final int LANECOMMENT = 15;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 43;
  public static final int VECTOR = 16;
  public static final int PCOMA = 41;
  public static final int EN = 28;
  public static final int PARR = 29;
  public static final int PUNTOP = 42;
  public static final int NO = 4;
  public static final int PUNTO = 35;
  public static final int VARIABLES = 23;
  public static final int PARL = 26;
  public static final int WHILE = 10;
  public static final int FALSO = 24;
  public static final int ASIGN = 45;
  public static final int DOSP = 40;
  public static final int BOOLEANO = 13;
  public static final int STRING = 19;
  public static final int PARA = 12;
  public static final int FINSI = 48;
  public static final int VAR = 25;
}

