/* The following code was generated by JFlex 1.4.1 on 9/15/19 10:38 PM */

package compiler.lexical;
import compiler.syntax.sym;
import compiler.lexical.Token;
import es.uned.lsi.compiler.lexical.ScannerIF;
import es.uned.lsi.compiler.lexical.LexicalError;
import es.uned.lsi.compiler.lexical.LexicalErrorManager;

//Produced by MV tools 2019-08-01 18:15:29
// incluir aqui, si es necesario otras importaciones


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 9/15/19 10:38 PM from the specification file
 * <tt>/home/faiya/eclipse-workspace/ArquitecturaPLI-2018-2019/doc/specs/scanner.flex</tt>
 */
public class Scanner implements java_cup.runtime.Scanner, ScannerIF {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 1;

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  5,  0,  4,  4,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    40,  0,  7,  6,  0,  0,  0,  0,  8,  9, 10, 11, 15, 12, 13,  0, 
     3,  3,  3,  3,  3,  3,  3,  3,  3,  3, 14, 16, 17, 18,  0,  0, 
     0, 28, 23, 33, 37, 31, 39, 27, 42, 34,  2,  2, 30, 29, 32, 26, 
    24,  2, 25, 21, 35, 22, 38, 41,  2, 43, 36, 19,  0, 20,  0,  2, 
     0, 28, 23, 33, 37, 31, 39, 27, 42, 34,  2,  2, 30, 29, 32, 26, 
    24,  2, 25, 21, 35, 22, 38, 41,  2, 43, 36,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\2\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\14\3\1\22\1\0\1\2\1\0"+
    "\1\23\1\24\1\25\1\3\1\26\4\3\1\27\1\30"+
    "\2\3\1\31\1\3\1\32\22\3\1\33\3\3\1\34"+
    "\2\3\1\35\3\3\1\36\14\3\1\0\13\3\1\37"+
    "\4\3\1\40\1\0\1\41\6\3\1\42\2\3\1\43"+
    "\2\3\1\44\1\3\1\45\12\3\1\46\1\3\1\47"+
    "\1\50\1\3\1\51\1\52\1\53\1\3\1\54\4\3"+
    "\1\55\2\3\1\56\2\3\1\57\1\3\1\60";

  private static int [] zzUnpackAction() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\54\0\54\0\130\0\204\0\260\0\334"+
    "\0\54\0\54\0\54\0\54\0\54\0\u0108\0\54\0\54"+
    "\0\54\0\54\0\u0134\0\54\0\54\0\u0160\0\u018c\0\u01b8"+
    "\0\u01e4\0\u0210\0\u023c\0\u0268\0\u0294\0\u02c0\0\u02ec\0\u0318"+
    "\0\u0344\0\130\0\260\0\260\0\334\0\334\0\54\0\54"+
    "\0\u0370\0\u039c\0\u03c8\0\u03f4\0\u0420\0\u044c\0\u0478\0\130"+
    "\0\u04a4\0\u04d0\0\130\0\u04fc\0\u0528\0\u0554\0\u0580\0\u05ac"+
    "\0\u05d8\0\u0604\0\u0630\0\u065c\0\u0688\0\u06b4\0\u06e0\0\u070c"+
    "\0\u0738\0\u0764\0\u0790\0\u07bc\0\u07e8\0\u0814\0\u0840\0\u086c"+
    "\0\u0898\0\u08c4\0\u08f0\0\u091c\0\u0948\0\u0974\0\130\0\u09a0"+
    "\0\u09cc\0\u09f8\0\130\0\u0a24\0\u0a50\0\u0a7c\0\u0aa8\0\u0ad4"+
    "\0\u0b00\0\u0b2c\0\u0b58\0\u0b84\0\u0bb0\0\u0bdc\0\u0c08\0\u0c34"+
    "\0\u0c60\0\u0c8c\0\u0cb8\0\u0ce4\0\u0d10\0\u0d3c\0\u0d68\0\u0d94"+
    "\0\u0dc0\0\u0dec\0\u0e18\0\130\0\u0e44\0\u0e70\0\u0e9c\0\u0ec8"+
    "\0\130\0\u0ef4\0\130\0\u0f20\0\u0f4c\0\u0f78\0\u0fa4\0\u0fd0"+
    "\0\u0ffc\0\130\0\u1028\0\u1054\0\130\0\u1080\0\u10ac\0\130"+
    "\0\u10d8\0\54\0\u1104\0\u1130\0\u115c\0\u1188\0\u11b4\0\u11e0"+
    "\0\u120c\0\u1238\0\u1264\0\u1290\0\130\0\u12bc\0\130\0\130"+
    "\0\u12e8\0\130\0\130\0\130\0\u1314\0\130\0\u1340\0\u136c"+
    "\0\u1398\0\u13c4\0\130\0\u13f0\0\u141c\0\130\0\u1448\0\u1474"+
    "\0\130\0\u14a0\0\130";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\2\4\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\5\1\27\1\30"+
    "\6\5\1\31\1\32\1\33\1\34\1\35\1\5\1\36"+
    "\1\37\1\40\1\4\1\41\1\5\1\42\56\0\2\5"+
    "\21\0\23\5\1\0\3\5\3\0\1\6\50\0\4\43"+
    "\1\44\1\4\46\43\5\45\1\0\1\45\1\46\44\45"+
    "\15\0\1\47\60\0\1\50\33\0\2\5\21\0\1\5"+
    "\1\51\13\5\1\52\5\5\1\0\3\5\2\0\2\5"+
    "\21\0\5\5\1\53\15\5\1\0\3\5\2\0\2\5"+
    "\21\0\4\5\1\54\2\5\1\55\13\5\1\0\3\5"+
    "\2\0\2\5\21\0\1\56\12\5\1\57\7\5\1\0"+
    "\3\5\2\0\2\5\21\0\5\5\1\60\15\5\1\0"+
    "\3\5\2\0\2\5\21\0\5\5\1\61\7\5\1\62"+
    "\5\5\1\0\3\5\2\0\2\5\21\0\22\5\1\63"+
    "\1\0\3\5\2\0\2\5\21\0\15\5\1\64\5\5"+
    "\1\0\3\5\2\0\2\5\21\0\12\5\1\65\10\5"+
    "\1\0\3\5\2\0\2\5\21\0\7\5\1\66\2\5"+
    "\1\67\10\5\1\0\3\5\2\0\2\5\21\0\1\5"+
    "\1\70\5\5\1\71\5\5\1\72\5\5\1\0\3\5"+
    "\2\0\2\5\21\0\23\5\1\0\1\5\1\73\1\5"+
    "\2\0\2\5\21\0\2\5\1\74\20\5\1\0\3\5"+
    "\2\0\2\5\21\0\13\5\1\75\7\5\1\0\3\5"+
    "\2\0\2\5\21\0\5\5\1\76\15\5\1\0\3\5"+
    "\2\0\2\5\21\0\5\5\1\77\15\5\1\0\3\5"+
    "\2\0\2\5\21\0\4\5\1\100\16\5\1\0\3\5"+
    "\2\0\2\5\21\0\14\5\1\101\6\5\1\0\3\5"+
    "\2\0\2\5\21\0\16\5\1\102\4\5\1\0\3\5"+
    "\2\0\2\5\21\0\10\5\1\103\2\5\1\104\7\5"+
    "\1\0\3\5\2\0\2\5\21\0\12\5\1\105\10\5"+
    "\1\0\3\5\2\0\2\5\21\0\3\5\1\106\17\5"+
    "\1\0\3\5\2\0\2\5\21\0\21\5\1\107\1\5"+
    "\1\0\3\5\2\0\2\5\21\0\4\5\1\110\16\5"+
    "\1\0\3\5\2\0\2\5\21\0\14\5\1\111\6\5"+
    "\1\0\3\5\2\0\2\5\21\0\13\5\1\112\7\5"+
    "\1\0\3\5\2\0\2\5\21\0\11\5\1\113\11\5"+
    "\1\0\3\5\2\0\2\5\21\0\13\5\1\114\7\5"+
    "\1\0\3\5\2\0\2\5\21\0\15\5\1\115\5\5"+
    "\1\0\3\5\2\0\2\5\21\0\3\5\1\116\17\5"+
    "\1\0\3\5\2\0\2\5\21\0\5\5\1\117\15\5"+
    "\1\0\3\5\2\0\2\5\21\0\11\5\1\120\11\5"+
    "\1\0\3\5\2\0\2\5\21\0\6\5\1\121\5\5"+
    "\1\122\6\5\1\0\3\5\2\0\2\5\21\0\7\5"+
    "\1\123\13\5\1\0\3\5\2\0\2\5\21\0\4\5"+
    "\1\124\16\5\1\0\3\5\2\0\2\5\21\0\5\5"+
    "\1\125\4\5\1\126\10\5\1\0\3\5\2\0\2\5"+
    "\21\0\15\5\1\127\5\5\1\0\3\5\2\0\2\5"+
    "\21\0\1\130\22\5\1\0\3\5\2\0\2\5\21\0"+
    "\4\5\1\131\16\5\1\0\3\5\2\0\2\5\21\0"+
    "\5\5\1\132\15\5\1\0\3\5\2\0\2\5\21\0"+
    "\5\5\1\133\15\5\1\0\3\5\2\0\2\5\21\0"+
    "\15\5\1\134\5\5\1\0\3\5\2\0\2\5\21\0"+
    "\16\5\1\135\4\5\1\0\3\5\2\0\2\5\21\0"+
    "\14\5\1\136\6\5\1\0\3\5\2\0\2\5\21\0"+
    "\1\137\22\5\1\0\3\5\2\0\2\5\21\0\23\5"+
    "\1\140\3\5\2\0\2\5\21\0\11\5\1\141\11\5"+
    "\1\0\3\5\2\0\2\5\21\0\4\5\1\142\16\5"+
    "\1\0\3\5\2\0\2\5\21\0\12\5\1\143\10\5"+
    "\1\0\3\5\2\0\2\5\21\0\4\5\1\144\16\5"+
    "\1\0\3\5\2\0\2\5\21\0\12\5\1\145\10\5"+
    "\1\0\3\5\2\0\2\5\21\0\15\5\1\146\5\5"+
    "\1\0\3\5\2\0\2\5\21\0\13\5\1\147\7\5"+
    "\1\0\3\5\2\0\2\5\21\0\4\5\1\150\16\5"+
    "\1\0\3\5\2\0\2\5\21\0\12\5\1\151\10\5"+
    "\1\0\3\5\2\0\2\5\21\0\16\5\1\152\4\5"+
    "\1\0\3\5\2\0\2\5\21\0\16\5\1\153\4\5"+
    "\1\0\3\5\2\0\2\5\21\0\1\154\22\5\1\0"+
    "\3\5\2\0\2\5\21\0\11\5\1\155\11\5\1\0"+
    "\3\5\2\0\2\5\21\0\7\5\1\156\13\5\1\0"+
    "\3\5\2\0\2\5\21\0\5\5\1\157\15\5\1\0"+
    "\3\5\2\0\2\5\21\0\15\5\1\160\5\5\1\0"+
    "\3\5\2\0\2\5\21\0\5\5\1\161\15\5\1\0"+
    "\3\5\25\0\1\162\30\0\2\5\21\0\12\5\1\163"+
    "\10\5\1\0\3\5\2\0\2\5\21\0\5\5\1\164"+
    "\15\5\1\0\3\5\2\0\2\5\21\0\7\5\1\165"+
    "\13\5\1\0\3\5\2\0\2\5\21\0\7\5\1\166"+
    "\13\5\1\0\3\5\2\0\2\5\21\0\20\5\1\167"+
    "\2\5\1\0\3\5\2\0\2\5\21\0\2\5\1\170"+
    "\20\5\1\0\3\5\2\0\2\5\21\0\14\5\1\171"+
    "\6\5\1\0\3\5\2\0\2\5\21\0\5\5\1\172"+
    "\15\5\1\0\3\5\2\0\2\5\21\0\13\5\1\173"+
    "\7\5\1\0\3\5\2\0\2\5\21\0\7\5\1\174"+
    "\13\5\1\0\3\5\2\0\2\5\21\0\5\5\1\175"+
    "\15\5\1\0\3\5\2\0\2\5\21\0\21\5\1\176"+
    "\1\5\1\0\3\5\2\0\2\5\21\0\2\5\1\177"+
    "\20\5\1\0\3\5\2\0\2\5\21\0\4\5\1\200"+
    "\16\5\1\0\3\5\2\0\2\5\21\0\5\5\1\201"+
    "\15\5\1\0\3\5\42\0\1\202\13\0\2\5\21\0"+
    "\6\5\1\203\14\5\1\0\3\5\2\0\2\5\21\0"+
    "\13\5\1\204\7\5\1\0\3\5\2\0\2\5\21\0"+
    "\10\5\1\205\12\5\1\0\3\5\2\0\2\5\21\0"+
    "\15\5\1\206\5\5\1\0\3\5\2\0\2\5\21\0"+
    "\15\5\1\207\5\5\1\0\3\5\2\0\2\5\21\0"+
    "\12\5\1\210\10\5\1\0\3\5\2\0\2\5\21\0"+
    "\17\5\1\211\3\5\1\0\3\5\2\0\2\5\21\0"+
    "\13\5\1\212\7\5\1\0\3\5\2\0\2\5\21\0"+
    "\12\5\1\213\10\5\1\0\3\5\2\0\2\5\21\0"+
    "\11\5\1\214\11\5\1\0\3\5\2\0\2\5\21\0"+
    "\13\5\1\215\7\5\1\0\3\5\2\0\2\5\21\0"+
    "\4\5\1\216\16\5\1\0\3\5\2\0\2\5\21\0"+
    "\5\5\1\217\15\5\1\0\3\5\2\0\2\5\21\0"+
    "\7\5\1\220\13\5\1\0\3\5\2\0\2\5\21\0"+
    "\10\5\1\221\12\5\1\0\3\5\2\0\2\5\21\0"+
    "\4\5\1\222\16\5\1\0\3\5\2\0\2\5\21\0"+
    "\1\223\22\5\1\0\3\5\2\0\2\5\21\0\5\5"+
    "\1\224\15\5\1\0\3\5\2\0\2\5\21\0\16\5"+
    "\1\225\4\5\1\0\3\5\2\0\2\5\21\0\4\5"+
    "\1\226\16\5\1\0\3\5\2\0\2\5\21\0\12\5"+
    "\1\227\10\5\1\0\3\5\2\0\2\5\21\0\7\5"+
    "\1\230\13\5\1\0\3\5\2\0\2\5\21\0\15\5"+
    "\1\231\5\5\1\0\3\5\2\0\2\5\21\0\12\5"+
    "\1\232\10\5\1\0\3\5\2\0\2\5\21\0\1\233"+
    "\22\5\1\0\3\5\2\0\2\5\21\0\10\5\1\234"+
    "\12\5\1\0\3\5\2\0\2\5\21\0\12\5\1\235"+
    "\10\5\1\0\3\5\2\0\2\5\21\0\1\236\22\5"+
    "\1\0\3\5\2\0\2\5\21\0\7\5\1\237\13\5"+
    "\1\0\3\5\2\0\2\5\21\0\13\5\1\240\7\5"+
    "\1\0\3\5\2\0\2\5\21\0\1\241\22\5\1\0"+
    "\3\5\2\0\2\5\21\0\16\5\1\242\4\5\1\0"+
    "\3\5\2\0\2\5\21\0\5\5\1\243\15\5\1\0"+
    "\3\5";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5324];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\10\2\11\4\1\5\11\1\1\4\11\1\1"+
    "\2\11\15\1\1\0\1\1\1\0\1\1\2\11\67\1"+
    "\1\0\21\1\1\0\17\1\1\11\41\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
 LexicalErrorManager lexicalErrorManager = new LexicalErrorManager ();
 private int commentCount = 0;
 int linecom=0;
 int columncom=0;
 int contadorstring=0;


 //Funcion para crear tokens

 Token createToken (int x)	{
 	Token token = new Token (x);
 	 token.setLine (yyline + 1);
 	 token.setColumn (yycolumn + 1);
 	 token.setLexema (yytext ());
 	 return token;
}

 LexicalError createError(String mensaje){
	LexicalError error = new LexicalError (mensaje);
	error.setLine (yyline + 1);
	error.setColumn (yycolumn + 1);
	error.setLexema (yytext ());
	lexicalErrorManager.lexicalError (mensaje);
	 return error;
}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) throws LexicalError {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new LexicalError(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  throws LexicalError {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException, LexicalError {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 8: 
          { return createToken (sym.PLUS);
          }
        case 49: break;
        case 4: 
          { return createToken (sym.NUM);
          }
        case 50: break;
        case 46: 
          { return createToken (sym.CONSTANTES);
          }
        case 51: break;
        case 14: 
          { return createToken (sym.LESS);
          }
        case 52: break;
        case 27: 
          { return createToken (sym.VAR);
          }
        case 53: break;
        case 13: 
          { return createToken (sym.PCOMA);
          }
        case 54: break;
        case 40: 
          { return createToken (sym.PROGRAMA);
          }
        case 55: break;
        case 19: 
          { return createToken (sym.STRING);
          }
        case 56: break;
        case 18: 
          { return createToken (sym.Y);
          }
        case 57: break;
        case 20: 
          { return createToken (sym.PUNTOP);
          }
        case 58: break;
        case 28: 
          { return createToken (sym.FIN);
          }
        case 59: break;
        case 35: 
          { return createToken (sym.CIERTO);
          }
        case 60: break;
        case 7: 
          { return createToken (sym.MULT);
          }
        case 61: break;
        case 1: 
          { LexicalError error = new LexicalError ();
		error.setLine (yyline + 1);
		error.setColumn (yycolumn + 1);
		error.setLexema (yytext ());
		lexicalErrorManager.lexicalError (error);
          }
        case 62: break;
        case 38: 
          { return createToken (sym.FUNCION);
          }
        case 63: break;
        case 12: 
          { return createToken (sym.COMA);
          }
        case 64: break;
        case 17: 
          { return createToken (sym.BRACKETR);
          }
        case 65: break;
        case 22: 
          { return createToken (sym.SI);
          }
        case 66: break;
        case 43: 
          { return createToken (sym.COMIENZO);
          }
        case 67: break;
        case 48: 
          { return createToken (sym.PROCEDIMIENTO);
          }
        case 68: break;
        case 45: 
          { return createToken (sym.VARIABLES);
          }
        case 69: break;
        case 33: 
          { return createToken (sym.WHILE);
          }
        case 70: break;
        case 44: 
          { return createToken (sym.DEVOLVER);
          }
        case 71: break;
        case 21: 
          { return createToken (sym.EQUALS);
          }
        case 72: break;
        case 42: 
          { return createToken (sym.ENTONCES);
          }
        case 73: break;
        case 11: 
          { return createToken (sym.DOSP);
          }
        case 74: break;
        case 25: 
          { return createToken (sym.IF);
          }
        case 75: break;
        case 24: 
          { return createToken (sym.NO);
          }
        case 76: break;
        case 9: 
          { return createToken (sym.MINUS);
          }
        case 77: break;
        case 5: 
          { return createToken (sym.PARL);
          }
        case 78: break;
        case 31: 
          { return createToken (sym.TIPOS);
          }
        case 79: break;
        case 26: 
          { return createToken (sym.DE);
          }
        case 80: break;
        case 32: 
          { return createToken (sym.FALSO);
          }
        case 81: break;
        case 36: 
          { return createToken (sym.VECTOR);
          }
        case 82: break;
        case 47: 
          { return createToken (sym.SUBPROGRAMAS);
          }
        case 83: break;
        case 41: 
          { return createToken (sym.ESCRIBIR);
          }
        case 84: break;
        case 3: 
          { return createToken (sym.ID);
          }
        case 85: break;
        case 34: 
          { return createToken (sym.ENTERO);
          }
        case 86: break;
        case 10: 
          { return createToken (sym.PUNTO);
          }
        case 87: break;
        case 30: 
          { return createToken (sym.PARA);
          }
        case 88: break;
        case 6: 
          { return createToken (sym.PARR);
          }
        case 89: break;
        case 37: 
          { return createToken (sym.FINSI);
          }
        case 90: break;
        case 15: 
          { return createToken (sym.ASIGN);
          }
        case 91: break;
        case 29: 
          { return createToken (sym.SINO);
          }
        case 92: break;
        case 16: 
          { return createToken (sym.BRACKETL);
          }
        case 93: break;
        case 39: 
          { return createToken (sym.BOOLEANO);
          }
        case 94: break;
        case 23: 
          { return createToken (sym.EN);
          }
        case 95: break;
        case 2: 
          { 
          }
        case 96: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
